[package]
name = "little-man-computer"
version = "0.1.0"
authors = ["W Gomes <w.gomes5521250@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
